FROM mcr.microsoft.com/dotnet/core/sdk:3.1
MAINTAINER Kaspars Mickevics (kaspars@fx.lv)
RUN git clone https://github.com/fxlv/tempy.git
WORKDIR /tempy
RUN dotnet clean
RUN dotnet restore
RUN dotnet build
RUN dotnet test
WORKDIR /tempy/TempyAPI
EXPOSE 5000
LABEL tempy_component=api
CMD [ "./start.sh" ]
